### ISSUE TITLE
I am trying to run it on Windows

### ISSUE THREAD

**Issue by o-bardiuk** [druxt/quickstart#108]
````
D:\www\xxx.localhost\drupal>php ./vendor/bin/drush  -y config:set simple_oauth.settings public_key ../keys/public.key

 // public_key key does not exist in simple_oauth.settings config. Do you want to create a new config key?: yes.

D:\www\xxx.localhost\drupal>php ./vendor/bin/drush -y config:set simple_oauth.settings private_key ../keys/private.key

 // private_key key does not exist in simple_oauth.settings config. Do you want to create a new config key?: yes.

D:\www\xxx.localhost\drupal>php ./vendor/bin/drush simple-oauth:generate-keys ../keys

[warning] openssl_pkey_export(): Cannot get key from parameter 1 KeyGenerator.php:25
 [error]  TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in openssl_pkey_get_details() (line 27 of D:\www\xxx.localhost\drupal\web\modules\contrib\simple_oauth\src\Service\KeyGenerator.php) #0 D:\www\xxx.localhost\drupal\web\modules\contrib\simple_oauth\src\Service\KeyGenerator.php(27): openssl_pkey_get_details(false)
#1 D:\www\xxx.localhost\drupal\web\modules\contrib\simple_oauth\src\Service\KeyGeneratorService.php(78): Drupal\simple_oauth\Service\KeyGenerator::generateKeys()
#2 D:\www\xxx.localhost\drupal\web\modules\contrib\simple_oauth\src\Commands\SimpleOauthCommands.php(72): Drupal\simple_oauth\Service\KeyGeneratorService->generateKeys('D:\\www\\xxx.lo...')
#3 [internal function]: Drupal\simple_oauth\Commands\SimpleOauthCommands->generateKeys('../keys', Array)
````

Now when I run

````
D:\www\shoom.localhost\nuxt>npm run dev

> quickstart-druxt-site@1.0.0 dev
> nuxt


 FATAL  DruxtAuth requires a clientId to be provided.                                                         03:32:14

  at ModuleContainer.NuxtModule (node_modules\druxt-auth\dist\index.ssr.js:22:11)
  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:239:34)
  at node_modules\@nuxt\utils\dist\utils.js:639:43
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:51:7)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:478:5)


   │   ✖ Nuxt Fatal Error                                    
   │   Error: DruxtAuth requires a clientId to be provided.  



D:\www\shoom.localhost\nuxt>

`````

Can somebody help me with this?

Maybe there is a dump of the database with all settings and dummy keys that I can use from this point?
I really don't want to dig into all of that OAuth stuff that I have no idea about.

**Comment by Decipher** [comment]
This should be sorted now, on `develop`.

Your first error was Simple OAuth's key generation failing in OpenSSL,
and the `DruxtAuth requires a clientId` that followed was the knock-on:
setup had stopped part way, so no consumer was ever created.

Rather than pretend the local backend works on Windows, `npm run setup`
now says so immediately and points at the three routes that do:

- the dev container (VS Code "Reopen in Container", or `devpod up .`),
- WSL2, running the same commands inside your distro,
- DDEV or Lando, with `BASE_URL` set to the container URL.

The local backend drives a PHP built-in server with `nohup`, `lsof`,
`ps` and `kill` and generates keys through OpenSSL, so making it work
natively on Windows is a much bigger piece of work than it looks. I would
rather be honest up front than fail half way through an install.

The second half of what you hit is fixed for everyone: a missing
`OAUTH_CLIENT_ID` now produces an actionable message instead of that
`DruxtAuth requires a clientId` error from inside a module. Several
related OAuth bugs turned up while I was on this - the consumer was
being created without its `client_id` and `grant_types` fields, and
Simple OAuth 6 needs a scope to exist before it will accept any
authorization request - so login on a fresh install genuinely works now,
with `npm run check:oauth` to confirm it.

Closing this, but please do reopen or comment if you try it and hit
something else. Windows feedback is genuinely useful here - it is the
setup I can least easily test.
